name: Publish Package to npmjs
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - run: yarn config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
      - run: yarn
      - run: yarn publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create changelog file
        run: cd scripts && node auto-changelog.js
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref }}
        run: |
          prerelease_flag=""

          if [[ "${{ github.ref }}" == 'refs/heads/release/'* ]]; then
            prerelease_flag="--prerelease"
          fi

          gh release create "$tag" -F CHANGELOG.md \
            --repo="$GITHUB_REPOSITORY" \
            --title="${{ steps.vars.outputs.tag }} ${tag#v}" \
            $prerelease_flag